CREATE USER FD_ADMIN with password 'welcome1';
GRANT CONNECT ON DATABASE flexdeploy TO FD_ADMIN;

create schema FD_ADMIN;
create schema FD AUTHORIZATION FD_ADMIN;
create schema FF AUTHORIZATION FD_ADMIN;

GRANT USAGE ON SCHEMA FD_ADMIN TO FD_ADMIN;
GRANT USAGE ON SCHEMA FD TO FD_ADMIN;
GRANT USAGE ON SCHEMA FF TO FD_ADMIN;