GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FD_ADMIN TO FD_ADMIN;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FD_ADMIN TO FD_ADMIN;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FD TO FD_ADMIN;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FD TO FD_ADMIN;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FF TO FD_ADMIN;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA FF TO FD_ADMIN;